### ISSUE TITLE
Netherlands Antilles is missing

### ISSUE THREAD

**Issue by Zazalt** [umpirsky/country-list#55] opened 2016-06-09 10:05 UTC
Netherlands Antilles is missing

https://en.wikipedia.org/wiki/Netherlands_Antilles
https://countrycode.org/netherlandsantilles

**Comment by umpirsky** [comment] 2016-06-09 10:10
Duplicate of https://github.com/umpirsky/country-list/issues/38#issuecomment-65212450.

**Closed by umpirsky** 2016-06-09 10:10 UTC
